# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bptrack', '0002_auto_20161016_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bp_measure',
            name='bp_measure_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
