# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 01:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bptrack', '0003_auto_20161016_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='bp_measure',
            name='bp_measure_time_of_day',
            field=models.CharField(choices=[('MO', 'Morning'), ('AF', 'Afternoon'), ('EV', 'Evening')], default='', help_text='Pick one of the categories depending on the time when the measure was taken', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bp_measure',
            name='bp_measure_date',
            field=models.DateField(default=datetime.date.today, help_text='Day when the measure was taken'),
        ),
        migrations.AlterField(
            model_name='bp_measure',
            name='bp_measure_max',
            field=models.IntegerField(help_text='Max pressure in mmHG'),
        ),
        migrations.AlterField(
            model_name='bp_measure',
            name='bp_measure_min',
            field=models.IntegerField(help_text='Min pressure in mmHG'),
        ),
        migrations.AlterField(
            model_name='bp_measure',
            name='bp_measure_note',
            field=models.CharField(help_text='Free text', max_length=255),
        ),
        migrations.AlterField(
            model_name='bp_measure',
            name='bp_measure_pulse',
            field=models.IntegerField(help_text='Pulse when the measure was taken'),
        ),
    ]
