# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-01 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160716_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='Author name', max_length=200),
            preserve_default=False,
        ),
    ]
