# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-31 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20171216_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='salutation',
            field=models.CharField(max_length=100),
        ),
    ]
